Book_Page ="xpath=//a[contains(text(),'Books')]"
Computer_Page ="xpath=//a[contains(text(),'Computers')]"
Electronic_Page ="xpath=//a[contains(text(),'Electronics')]"
Apprisal_Page ="xpath=//a[contains(text(),'Apparel & Shoes')]"
Digital_Download_Page ="xpath=//a[contains(text(),'Digital downloads')]"
Jewelry_Page="xpath=//a[contains(text(),'Jewelry')]"
Gift_Card_Page ="xpath=//a[contains(text(),'Gift Cards')]"
Book_Page_Verification ="xpath=//strong[contains(text(),'Books')]"
Computer_Page_Verification ="xpath=//strong[contains(text(),'Computers')]"
Electronic_Page_Verification ="xpath=//strong[contains(text(),'Electronics')]"
Apprisal_Page_Verification ="xpath=//strong[contains(text(),'Apparel & Shoes')]"
Digital_Download_Page_Verification ="xpath=//strong[contains(text(),'Digital downloads')]"
Jewelry_Page_Verification ="xpath=//strong[contains(text(),'Jewelry')]"
Gift_Card_Page_Verification ="xpath=//strong[contains(text(),'Gift Cards')]"
